export interface Bill {
    supplierId: string;
    supplierDisplayName:string;
    billNumber: string;
    supplierInvoiceNum:string;
    sourceOfSupply: string;
    destinationOfSupply: string;
    taxMode: string;
    orderNumber: string;
    purchaseOrderDate: string;
    expectedShipmentDate: string;
    paymentTerms: string;
    paymentMode: string;
    PaidThrough:string;
    billDate: string;
    dueDate: string;
    items: {
        itemId: string;
        itemName: string;
        itemQuantity: number | string ;
        itemCostPrice: number | string ;
        itemDiscount: number | string ;
        itemDiscountType: string;
        itemTax:number | string ;
        itemSgst: number | string ;
        itemCgst: number | string ;
        itemIgst: number | string ;
        itemVat: number | string ;
        itemSgstAmount: number | string ;
        itemCgstAmount: number | string ;
        taxPreference:string;
        purchaseAccountId:string;
    }[];
    otherExpenseAmount: number | string ;
    otherExpenseAccountId:string;
    otherExpenseReason: string;
    vehicleNo: string;
    freightAmount: number | string ;
    freightAccountId:string;
    addNotes: string;
    termsAndConditions: string;
    attachFiles: string;
    subTotal: number | string ;
    totalItem: number | string ;
    sgst: number | string ;
    cgst: number | string ;
    igst:number | string ;
    transactionDiscountType: string;
    transactionDiscount: number | string ;
    transactionDiscountAmount: number | string ;
    totalTaxAmount: number | string ;
    itemTotalDiscount: number | string ;
    roundOffAmount: number | string ;
    paidStatus: string;
    shipmentPreference: string;
    grandTotal: number | string ;
    balanceAmount:number | string ;
    paidAmount:number | string ;
    paidAccountId:string;
    purchaseOrderId?:string;
}
